### ISSUE TITLE
Suporting PhotonVision 2024.3.1?

### ISSUE THREAD

**Issue by swalberg** [PlayingWithFusion/SnakeEyesDocs#11]
I downloaded the Release_18 image and flashed it to a Raspberry Pi 4. It booted and worked fine. I then went through the offline update procedure to upgrade to the latest Linuxarm64 version of PhotonVision. It boots, but can't see the camera (only shows "placeholder camera"), nor do any of the stats show:

![image](https://github.com/PlayingWithFusion/SnakeEyesDocs/assets/221368/cc7e41fa-8135-4883-827f-7439bc597dc9)

I do see some shared library problems in the logs:

```
Mar 27 10:24:08 photonvision java[1688]: [2024-03-27 10:24:08] [Camera - MrCalJNILoader] [ERROR] Couldn't load shared object mrcal_jni: /tmp/libmrcal_jni.so: libsuitesparseconfig.so.5: cannot open shared object file: No such file or directory
Mar 27 10:24:08 photonvision java[1688]: [2024-03-27 10:24:08] [Camera - LibCameraJNILoader] [ERROR] Couldn't load shared object photonlibcamera: /tmp/libphotonlibcamera.so: libcamera.so.0.1: cannot open shared object file: No such file or directory
```

Other interesting logs:

```
Mar 27 10:24:14 photonvision java[1688]:         at java.base/java.lang.Thread.run(Thread.java:829)
Mar 27 10:24:14 photonvision java[1688]:         at org.photonvision.common.dataflow.DataChangeService.dispatchFromQueue(DataChangeService.java:65)
Mar 27 10:24:14 photonvision java[1688]:         at org.photonvision.server.UIInboundSubscriber.onDataChangeEvent(UIInboundSubscriber.java:46)
Mar 27 10:24:14 photonvision java[1688]:         at org.photonvision.common.configuration.PhotonConfiguration.toHashMap(PhotonConfiguration.java:138)
Mar 27 10:24:14 photonvision java[1688]:         at org.photonvision.raspi.LibCameraJNILoader.isSupported(LibCameraJNILoader.java:77)
Mar 27 10:24:14 photonvision java[1688]:         at org.photonvision.raspi.LibCameraJNI.isSupported(LibCameraJNI.java:65)
Mar 27 10:24:14 photonvision java[1688]:         at org.photonvision.raspi.LibCameraJNI.isLibraryWorking(Native Method)
Mar 27 10:24:14 photonvision java[1688]: Exception in thread "DataChangeEventDispatchThread" java.lang.UnsatisfiedLinkError: 'boolean org.photonvision.raspi.LibCameraJNI.isLibraryWorking()'
```

**Comment by swalberg** [comment]
```
root@photonvision:/var/log# find / -name libcamera.so\*
/usr/lib/aarch64-linux-gnu/libcamera.so.0.0.3
root@photonvision:/var/log# find / -name libsuitesparseconfig.so\*
root@photonvision:/var/log#
```
